### ISSUE TITLE
Duplicate Values being pushed 

### ISSUE THREAD

**Issue by somaniab** [etishor/Metrics.NET#102]
Hi ,

Suppose i have set and interval of 60 seconds , and i am collecting metrics for login . First 60 seconds user logs in , and entry is pushed . now next 60 seconds , user does not do anything , still the same entry is pushed . how can i avoid duplicates ?

**Comment by somaniab** [comment]
can i use ResetMetricsValues method to fix this ?

**Comment by realrs** [comment]
Hi!

Can you add more details: how you metric configured, how and what are you observe metric value?

**Comment by somaniab** [comment]
I have solved the issue by using CounterValueSource , and resetting the value while reading it .
