### ISSUE TITLE
Metrics.Nancy fails using private probing path

### ISSUE THREAD

**Issue by rbirkby** [etishor/Metrics.NET#45]
If I deploy the Metrics.Nancy assembly in a subfolder (eg /lib) and use a private probing path, the /Metrics/ endpoint fails to be registered.

For example, in the app.config, set the private probing path with:

``` xml
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <probing privatePath="lib" />
```

and then deploying the Metrics.Nancy assembly into the lib folder, results in a 404 on the /Metrics/ endpoint. However, the main Metrics.Net assembly works fine when deployed into this /lib/ private probing location.

**Comment by bitbonk** [comment]
I have come across a similar issue where my modules should be autodiscovered and each resided in its own subdirectory. I have added all those subdirectories into `probing privatePath` but nancy did not find them. It would be really cool if Nancy would support that. Unfortunately `AppDomain.CurrentDomain.SetupInformation.PrivateBinPath` is always null for the primary/default appdomain.
