### ISSUE TITLE
MetricsContext does not return metric reference for Gauges or PerfCounters

### ISSUE THREAD

**Issue by Paccc** [etishor/Metrics.NET#55]
The methods to create a gauge or performance counter metric don't return a reference to the metric that was just created, unlike all the other methods to create a metric.  Is this a bug, or is this intentional?

Also, it doesn't look like there's any way to dispose the performance counter instance that's created by the PerformanceCounterGauge, which doesn't implement IDisposable. Would it make sense to expose the perf counter reference as a property on the gauge? I could then dispose it manually when I'm done using it. This would additionally be useful to me because I want to access some of the performance counter's properties, specifically, its name, category, instance name, help text, and counter type.  Also, shouldn't PerformanceCounterGauge derive from GaugeImplementation?

Another unrelated thing I noticed, it seems like DerivedGauge is essentially identical to ScaledValueProvider<T> with T : double. Is that the only difference, or am I misunderstanding something?

Thanks!

**Comment by etishor** [comment]
Closing this for now, feel free to re-open if more info is needed.
