### ISSUE TITLE
RequiresAuthentication in OWIN

### ISSUE THREAD

**Issue by jfritchman** [etishor/Metrics.NET#56]
I see that there is a method to require authentication if you are using Nancy.  Is there similar functionality in OWIN?

**Comment by alhardy** [comment]
No, at the moment authentication has not yet been implemented for the OWIN adapter. 

Iulian, looks like you have started something for the Nancy adapter, how are you planning to go about authentication?

**Comment by etishor** [comment]
@alhardy I really don't want to do any authentication/security related functionality directly in the Metrics library. Metrics library should easily integrate with any existing frameworks/applications/libraries that provide authentication and authorization functionality.  

The Nancy method for authentication is provided by Nancy and not by the Metrics library. The Nancy adapter in the Metrics library just provides an easy way to the user to call the auth related methods exposed by Nancy.

As for Owin, I'm not an expert, but it is my understanding that the whole point of Owin is to be able to define and compose independent middlewares each providing different functionality. If I'm not mistaken then authentication should be handled by an authentication middleware. 

A quick google check seems to confirm that: 

http://blogs.msdn.com/b/webdev/archive/2013/07/03/understanding-owin-forms-authentication-in-mvc-5.aspx
http://coding.abel.nu/2014/06/writing-an-owin-authentication-middleware/

If you have any issues integrating Metrics with such middleware implementation do let us know.

**Comment by etishor** [comment]
@jfritchman @alhardy i'm closing this for now, but feel free to re-open if more information can be added.
