### ISSUE TITLE
Reading metrics data using pure c#

### ISSUE THREAD

**Issue by BorysBe** [etishor/Metrics.NET#57]
1. How to get access to metrics data directly - using c# (to read and process data) instead reading it by human via web page ? 

2. How to get statistics (in c# mostly):
a) how many counts per hour/ minute/ second (in various version of calculating - average, EWMA)
b) how to get those statistics (counts is per hour/ minute/ second and total counts) for different contexts (users?)?

**Comment by etishor** [comment]
I have not thought about this much, but you can directly access metrics data by using:

```csharp
Metric.Context(null).DataProvider.CurrentMetricsData
```

As for point 2. (I'm not sure I understand the question) the library provides ways of capturing the metrics (counts, rates, timers etc) and provides a basic view of these metrics (1min, 5min avg etc). The available stats for each metric are described in [the docs](https://github.com/etishor/Metrics.NET/wiki/Available-Metrics).

To perform aggregations and more complex analytics you need to use an external persistent storage like [Graphite](https://github.com/etishor/Metrics.NET/wiki/Graphite-Report) or [InfluxDb](https://github.com/etishor/Metrics.NET/wiki/InfluxDb). These two are unfortunately not trivial to setup on windows and the Metrics.NET adapters for them have not been extensively tested (but should work).

If you can maybe provide an example of what you are trying to accomplish, I might be able to provide more ideas.

Iulian

**Comment by BorysBe** [comment]
I am not expert, but as far I know - In danielcrenna/metrics-net there was various counters connected to histogram (it has certain ammount of samples). There was a counter PerSecondCounterMetric (but we could easily adopt it, and change  EWMA _ewma = EWMA.OneSecondEWMA(); into  EWMA _ewma = EWMA.OneMinuteEWMA();)

During every update of this PerSecondCounterMetric and histogram - all histogram samples was updated.
For PerSecondCounterMetric we received EWMA statistics per second - exponentially-weighted moving average chart (probably it is useful for notice all values which are not a noise) 
I would like to achieve similar effect in your libraray. 

So...
(1) I want to draw 2 charts 
- one with "standard" average (refers to the sum of a list of numbers divided by the size of the list) requests counts / per second.
- second - with EWMA average counts / per second.

And I would like to configure  if I need 

EWMA.OneMinuteEWMA();
EWMA.FiveMinuteEWMA();
EWMA.FifteenMinuteEWMA();

(1b) I would like to expand range of EWMA into OneHourEWMA and OneDayEWMA

It seems - EWMA is a standard way of displaying data,
(2) Another question is - how to display time units on chart view on Web Page?

**Comment by etishor** [comment]
Sorry for the delay, I'll get back to you as soon as possible. Not sure if it would help you, but maybe you can try using the Metrics classes directly in your code? Take a look in the Metrics.Core namespace. Or maybe use the Metrics.Utils.EWMA class directly.

**Comment by etishor** [comment]
On the latest dev branch, there is a new class [ValueReader](https://github.com/etishor/Metrics.NET/blob/dev/Src/Metrics/MetricData/ValueReader.cs) that you can use do get the current data for a meteric. 

Hope this helps. If not you will need to provide more details, maybe a code sample of what you are trying to do.
