### ISSUE TITLE
Configure interval

### ISSUE THREAD

**Issue by o-mdr** [etishor/Metrics.NET#59]
I would like to configure interval through a config value, like
```
<appSettings>
    <add key="Metrics.CSV.Interval.Seconds" value="10"/>
</appSettings>
```
However, I am still required to pass the same value to the API call if I use csv 
```
Metric.Config
 .WithErrorHandler(x => ErrorLog.Error(x))
 .WithReporting(cfg => cfg.WithCSVReports(OutDir, >>>> TimeSpan.FromSeconds(1) <<<<< ));  
``` 

No mater what I set in config, the code value will always dominate

**Comment by etishor** [comment]
I can't test this right now, but the intention was that if you specify the config option you don't have to specify it in code. Try removing the .WithCSVReports() line.

**Comment by o-mdr** [comment]
That worked. For other's benefit I used this config values
````
<appSettings>
    <add key="Metrics.CSV.Interval.Seconds" value="1"/>
    <add key="Metrics.CSV.Path" value="Diagnostics\Metrics\"/>
</appSettings>
````
And in code
````
public class PerfTracker
{
    private static readonly ILog ErrorLog = LogManager.GetLogger("Error");
        
    public static void Setup()
    {
        Metric.Config.WithErrorHandler(x => ErrorLog.Error(x));
    }
}
````

**Comment by etishor** [comment]
Awesome, thanks for the details. I'll see if it is worth to change the docs to mention this.
