### ISSUE TITLE
How to monitor Process CPU usage

### ISSUE THREAD

**Issue by o-mdr** [etishor/Metrics.NET#60]
I am trying to figure out how to get performance a counter for CPU usage of my application. I noticed this line in [PerformanceCounter.cs](https://github.com/etishor/Metrics.NET/blob/master/Src/Metrics/PerfCounters/PerformanceCounters.cs)

````
context.Register("CPU Usage", Unit.Custom("%"), "Processor", 
 "% Processor Time", TotalInstance, tags: "cpu");
````
But it is for the whole OS. How can I get similar counter for my process? Thanks.

**Comment by etishor** [comment]
I remember looking for something similar.

Take a look at [this](http://weblogs.thinktecture.com/ingo/2004/06/getting-the-current-process-your-own-cpu-usage.html) and [this](http://stackoverflow.com/questions/9115436/performance-counter-by-process-id-instead-of-name) and [this](https://msdn.microsoft.com/en-us/library/system.diagnostics.process.privilegedprocessortime(v=vs.110).aspx).

**Comment by o-mdr** [comment]
I take it, I cannot just use Metrics with something like
````
Metric.PerformanceCounter("Process total usage", 
 >>> "Process" <<<, "% Processor Time", "_Total", Unit.Custom("%"));
````
If I do that, I get values
````
790.36%
797.91%
797.96%
````
Which on my 8 core machine could indicate that CPU is maxed, however in process explorer it barely uses 5% of a single core, as in my test I just sleep and let the Metrics write down values every second.

**Comment by o-mdr** [comment]
I figured out what I did wrong. It was the *instance name*. For others, instance name is effectively your process name. I resolved it like this (just remove >>> and <<< to complile):

```` csharp
string app = Process.GetCurrentProcess().ProcessName;
Metric.PerformanceCounter("Process total usage", "Process", "% Processor Time", 
  >>> app <<<, Unit.Custom("%"));

// and a few other useful metrics
Metric.PerformanceCounter("Working Set", "Process", "Working Set",  
  app, Unit.Bytes);
Metric.PerformanceCounter("IO Data Operations/sec", "Process", "IO Data Operations/sec", 
  app, Unit.Custom("IOPS"));
Metric.PerformanceCounter("IO Other Operations/sec", "Process", "IO Other Operations/sec", 
  app, Unit.Custom("IOPS"));
````

I tried to find a sample with good counters, but couldn't find any. I could create a pull request if you'd be interested in it?

**Comment by etishor** [comment]
Thanks, feel free to submit a PR to the [pre-configured app counters](https://github.com/etishor/Metrics.NET/blob/master/Src/Metrics/PerfCounters/PerformanceCounters.cs#L52) as I think this information is general and useful enough for all users.
