### ISSUE TITLE
Ability to stop a specific report

### ISSUE THREAD

**Issue by alhardy** [etishor/Metrics.NET#64]
Is it possible to have a report associated with a registered remote so that on shutting down a metrics context the report is also stopped and disposed?

**Comment by etishor** [comment]
At the moment, I think you could do that by manually creating and disposing the report. Take a look at ScheduledReport and how MetricsReports are handling them. 

To be honest, the current reports architecture could use a new iteration.

**Comment by alhardy** [comment]
I was able to create a ScheduledReport and dispose of it to shut it down. I had to add an overload to MetricsReport to have this added to the report collection. Thanks
