### ISSUE TITLE
Q: How do I get the reports created on application shutdown?

### ISSUE THREAD

**Issue by mattiasw2** [etishor/Metrics.NET#69]
The web interface is really nice, but it would be nice to get the reports automatically at end of execution. Is there some kind of hook for this?

**Comment by etishor** [comment]
@mattiasw2 I'm not sure if this is what you mean by "get the reports", but you can manually run a report by using something like this:

```csharp
var data = Metric.Context(string.Empty).DataProvider.CurrentMetricsData; 
new ConsoleReport().RunReport(data, () => HealthChecks.GetStatus(), CancellationToken.None);
new StringReport().RunReport(data, () => HealthChecks.GetStatus(), CancellationToken.None);
```

**Comment by etishor** [comment]
Closing this for now, let me know if you need more info.

**Comment by mattiasw2** [comment]
Yes, that was what I was looking for. Thanks!
