### ISSUE TITLE
owin adapter

### ISSUE THREAD

**Issue by alhardy** [etishor/Metrics.NET#71]
We've been using the owin adapter in production for many of our services  for some time, all looks well, do you mind us bumping the package to version 1?

**Comment by etishor** [comment]
Hi @alhardy 

I have re-published the version from the master branch as v0.2.16 - the same version as the core Metrics library. 

For the future, let me know which options work best for you:

1. Keep Owin.Metrics as a separate package
2. Merge Owin.Metrics in the main Metrics library (as it has not external dependencies i'm fine with this)

If kept separately I think the best option is to use the same version ( 0.2.16 for now ) as the core Metrics library (like the Nancy adapter). If you want I can also push a 1.0.0 version for the Owin adapter but I think it is a bit less confusing if it has the same version as the Metrics library.

**Comment by alhardy** [comment]
I'm happy with separate packages. Agreed in keeping versions in sync. Thanks.

**Comment by etishor** [comment]
Roger that. Will keep separate package, with the same version as the core lib.
