### ISSUE TITLE
Total elapsed time in a timer

### ISSUE THREAD

**Issue by erik-kallen** [etishor/Metrics.NET#72]
When I create a timer (```Metric.Timer("Some value", Unit.Requests)```), In the web GUI I get the option to see graphs for count, requests/s, last value, min/max, percentiles and active sessions. All of these are great to have, but I think it would also be very useful to have a graph for total time spent. Is that possible?

**Comment by etishor** [comment]
Hi @erik-kallen,

You mean the sum of the duration of each recorded request? I'm not sure how useful such metric would be for most timer measurements. If you really wish to measure that you can add a counter that will sum all the durations:

```csharp
private static readonly Counter totalDuration = Metric.Counter("Total Duration", Unit.Custom("ms"))

using(var ctx = timer.NewContext())
{
    // perform operation that is measured by the timer
    
    totalDuration.Increment((long)context.Elapsed.TotalMilliseconds);
}
```

**Comment by erik-kallen** [comment]
Yes, your solution will most likely work, thanks.

The reason I want it (which is the reason I found Metrics.Net in the first place) is that I am experiencing performance problems in my application. In this case I need to know what my application is spending time on. I agree that total time taken in a timer by itself is probably not too useful, but if I have 10 of those timers I can compare the total time taken values for those timers to find out in which part of the application time actually gets spent.

**Comment by etishor** [comment]
I'll close this for now, let me know if you need more info.

**Comment by erik-kallen** [comment]
Sure, but I still vote for the feature. It is an important metric to have when profiling.

**Comment by etishor** [comment]
Roger that. With the new, optimized LongAdder or ThreadLocalLongAdder from ConcurrentUtils I think I might just add a total time counter, as the hit should be very low. Check out commit https://github.com/etishor/Metrics.NET/commit/d79cc0a07f096e660121a0320866f83cc760886c on the [feature/timer-track-total-time](https://github.com/etishor/Metrics.NET/tree/feature/timer-track-total-time) branch. Not yet finalized, but should work.

**Comment by erik-kallen** [comment]
Thanks.

Really great project btw!
