### ISSUE TITLE
Prometheus and 'pull' reports

### ISSUE THREAD

**Issue by smalldave** [etishor/Metrics.NET#81]
Are there any plans to support servers that pull report data?
Any suggestions for how to go about it?
Happy to have a stab at it if somebody wants to give me some pointers.

**Comment by etishor** [comment]
Currently, if you use HttpMetricsEndpoint the current metric values are exposed [over http as JSON](https://github.com/etishor/Metrics.NET/wiki/Http-Endpoint-with-Charting-App).

There are no current plans to implement support for Prometheus, but I would gladly accept a PR for it.

Take a look at [MetricsHttpListener](https://github.com/etishor/Metrics.NET/blob/master/Src/Metrics/Visualization/MetricsHttpListener.cs) class for inspiration. I think prometheus expects metrics serialized with proto-buf. 

You can also take a look at @andrasm .net client https://github.com/andrasm/prometheus-net

Prometheus looks very promising, in the future, if time permits I might take a look at it - especially if it will run on windows.

**Comment by smalldave** [comment]
Thanks. HttpMetricsEndpoint looks like a good starting point
