### ISSUE TITLE
Does Custom Reporter Class Blocks the execution of current method

### ISSUE THREAD

**Issue by somaniab** [etishor/Metrics.NET#95]
I want to measure time and counter for a particular . I have created a CustomReporter by Extending BaseReport class and getting data in ReportCounter and ReportTimer methods . Suppose there is some issue in  these methods and it is stuck . Does this block the execution of main method as well ? I mean Metric Reporter class executes in different thread right ?

**Comment by etishor** [comment]
Reports are executed using Task.Factory.StartNew() and will not block the main execution thread.

**Comment by somaniab** [comment]
thanks for clarifying.
